<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <OutputType>Exe</OutputType>

    <TargetFramework>net8.0-windows</TargetFramework>

    <ImplicitUsings>enable</ImplicitUsings>

    <Nullable>enable</Nullable>

    <PlatformTarget>x64</PlatformTarget>

    <RootNamespace>HalconLatticePickTest</RootNamespace>

    <IndustrialVisionToolsProj>$(MSBuildThisFileDirectory)..\..\XVCalibrate\IndustrialVisionTools\IndustrialVisionTools.csproj</IndustrialVisionToolsProj>

    <IndustrialVisionToolsObj>$(MSBuildThisFileDirectory)..\..\XVCalibrate\IndustrialVisionTools\obj\$(Configuration)\$(TargetFramework)\IndustrialVisionTools.dll</IndustrialVisionToolsObj>

  </PropertyGroup>

  <Target Name="CompileIndustrialVisionTools" BeforeTargets="ResolveAssemblyReferences">

    <MSBuild Projects="$(IndustrialVisionToolsProj)" Targets="CoreCompile" Properties="UseAppHost=false;Configuration=$(Configuration);Platform=$(Platform)" />

  </Target>

  <ItemGroup>

    <Reference Include="IndustrialVisionTools">

      <HintPath>$(IndustrialVisionToolsObj)</HintPath>

      <Private>true</Private>

    </Reference>

  </ItemGroup>

</Project>

